# DO NOT EDIT - This file is automatically generated
# Make changes to Manifest.txt and/or Rakefile and regenerate
# -*- encoding: utf-8 -*-
# stub: fattr 3.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "fattr".freeze
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Ara T. Howard".freeze]
  s.date = "2016-12-14"
  s.description = "fattr.rb is a \"fatter attr\" for ruby   The implementation of fattr.rb borrows many of the best ideas from the metakoans.rb ruby quiz     http://www.rubyquiz.com/quiz67.html   In particular the solutions of Christian Neukirchen and Florian Gross along with concepts from my original traits.rb lib   Key features provided by fattrs are:     * ability to specify default values for attrs and definition time.  values       can be literal objects or blocks, which are evaluated in the context of       self to initialize the variable     * classes remember which fattrs they've defined and this information is       available to client code     * a whole suite of methods is defined by calls to #fattrs including       getter, setter, query (var?) and banger (var! - which forces       re-initialization from the default value/block)     * ability to define multiple fattrs at once using key => value pairs     * fast lookup of whether or not a class has defined a certain fattr     * fattrs can be defined on objects on a per singleton basis     * getters acts as setters if an argument is given to them     * block caching, calling an fattr with a block sets the instance       variable to that block     * shortcuts for adding class/module level fattrs     * class inheritable attributes   all this in 156 lines of code".freeze
  s.email = "ara.t.howard@gmail.com".freeze
  s.extra_rdoc_files = ["Manifest.txt".freeze, "README.md".freeze]
  s.files = ["LICENSE".freeze, "Manifest.txt".freeze, "README.md".freeze, "Rakefile".freeze, "lib/fattr.rb".freeze, "lib/fattr/attribute.rb".freeze, "lib/fattr/attribute_parser.rb".freeze, "lib/fattr/attribute_set.rb".freeze, "lib/fattr/globally.rb".freeze, "lib/fattr/version.rb".freeze, "samples/a.rb".freeze, "samples/b.rb".freeze, "samples/c.rb".freeze, "samples/d.rb".freeze, "samples/e.rb".freeze, "samples/f.rb".freeze, "samples/g.rb".freeze, "samples/h.rb".freeze, "samples/i.rb".freeze, "tasks/default.rake".freeze, "tasks/this.rb".freeze, "test/test_attribute_parser.rb".freeze, "test/test_fattr.rb".freeze, "test/test_helper.rb".freeze, "test/test_version.rb".freeze]
  s.homepage = "http://github.com/ahoward/fattr".freeze
  s.licenses = ["MIT".freeze]
  s.rdoc_options = ["--main".freeze, "README.md".freeze, "--markup".freeze, "tomdoc".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.0.0".freeze)
  s.rubygems_version = "2.5.2".freeze
  s.summary = "fattr.rb is a \"fatter attr\" for ruby".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>.freeze, ["~> 10.3"])
      s.add_development_dependency(%q<minitest>.freeze, ["~> 5.7"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 4.1"])
      s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.10"])
    else
      s.add_dependency(%q<rake>.freeze, ["~> 10.3"])
      s.add_dependency(%q<minitest>.freeze, ["~> 5.7"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 4.1"])
      s.add_dependency(%q<simplecov>.freeze, ["~> 0.10"])
    end
  else
    s.add_dependency(%q<rake>.freeze, ["~> 10.3"])
    s.add_dependency(%q<minitest>.freeze, ["~> 5.7"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 4.1"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.10"])
  end
end
